
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type CloudFormationExecuteChangeSetInput = {
    awsCredentials: string
    regionName: string
    changeSetName: string
    stackName: string
    noFailOnEmptyChangeSet: boolean
    deleteEmptyChangeSet: boolean
    outputVariable: string
    captureStackOutputs: 'ignore' | 'asVariables' | 'asJSON'
    captureAsSecuredVars: boolean
    logRequest: boolean
    logResponse: boolean
}

export type CloudFormationExecuteChangeSetMessages = 
    | 'ExecutingChangeSet'
    | 'DeletingChangeSet'
    | 'ExecutionSkipped'
    | 'ExecuteChangeSetFailed'
    | 'WaitingForStackUpdate'
    | 'WaitingForStackCreation'
    | 'StackUpdated'
    | 'StackCreated'
    | 'StackUpdateFailed'
    | 'StackCreationFailed'
    | 'SettingOutputVariable'
    | 'ChangeSetDoesNotExist'
    | 'TaskCompleted'
    | 'CreatingStackOutputVariable'
    | 'ProcessingStackOutputsToBuildVariables'
    | 'ProcessingStackOutputsToJsonBlobBuildVariable'
    | 'SkippingStackOutputsProcessing'
    | 'FailedToObtainStackStatus'
    | 'ErrorRetrievingStackOutputs'
