
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type S3UploadInput = {
    awsCredentials: string
    regionName: string
    bucketName: string
    sourceFolder: string
    globExpressions: string
    targetFolder: string
    filesAcl: 'private' | 'public-read' | 'public-read-write' | 'authenticated-read' | 'aws-exec-read' | 'bucket-owner-read' | 'bucket-owner-full-control'
    createBucket: boolean
    keyManagement: 'none' | 'awsManaged' | 'customerManaged'
    encryptionAlgorithm: 'KMS' | 'AES256'
    kmsMasterKeyId: string
    customerKey: string
    flattenFolders: boolean
    contentType: string
    contentEncoding: string
    storageClass: 'STANDARD' | 'STANDARD_IA' | 'REDUCED_REDUNDANCY'
    forcePathStyleAddressing: boolean
    cacheControl: string
    logRequest: boolean
    logResponse: boolean
}

export type S3UploadMessages = 
    | 'FoundNFiles'
    | 'AllPaths'
    | 'MatchedPaths'
    | 'MatchedFiles'
    | 'NoMatchingFilesFound'
    | 'CreateBucketFailure'
    | 'BucketCreated'
    | 'UploadingFile'
    | 'FileUploadCompleted'
    | 'FileUploadFailed'
    | 'TaskCompleted'
    | 'UploadingFiles'
    | 'BucketNotExistNoAutocreate'
    | 'BucketNotExistCreating'
    | 'InvalidExpression'
