
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type LambdaDeployFunctionInput = {
    awsCredentials: string
    regionName: string
    deploymentMode: 'codeonly' | 'codeandconfiguration'
    functionName: string
    description: string
    functionHandler: string
    runtime: 'provided' | 'dotnetcore3.1' | 'dotnetcore2.1' | 'go1.x' | 'java8' | 'java11' | 'nodejs10.x' | 'nodejs12.x' | 'python2.7' | 'python3.6' | 'python3.7' | 'python3.8' | 'ruby2.5'
    codeLocation: 'localfile' | 's3object'
    localZipFile: string
    s3Bucket: string
    s3ObjectKey: string
    s3ObjectVersion: string
    roleARN: string
    memorySize: string
    timeout: string
    publish: boolean
    layers: string
    deadLetterARN: string
    kmsKeyARN: string
    environment: string
    tags: string
    securityGroups: string
    subnets: string
    tracingConfig: 'XRay' | 'Active' | 'PassThrough'
    outputVariable: string
    logRequest: boolean
    logResponse: boolean
}

export type LambdaDeployFunctionMessages = 
    | 'CreatingFunction'
    | 'UpdatingFunctionCode'
    | 'UpdatingFunctionConfiguration'
    | 'FunctionNotFound'
    | 'TaskCompleted'
    | 'AddingTag'
    | 'NoFunctionArnReturned'
    | 'SettingOutputVariable'
    | 'AwaitingStatus'
    | 'AwaitingStatusComplete'
    | 'CantWaitWarning'
