
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type LambdaNETCoreDeployInput = {
    awsCredentials: string
    regionName: string
    command: 'deployFunction' | 'deployServerless'
    packageOnly: boolean
    packageOutputFile: string
    lambdaProjectPath: string
    functionName: string
    functionRole: string
    functionHandler: string
    functionMemory: number
    functionTimeout: number
    stackName: string
    s3Bucket: string
    s3Prefix: string
    additionalArgs: string
}

export type LambdaNETCoreDeployMessages = 
    | 'DeployingProjectAt'
    | 'ReadingDefaultSettingsFile'
    | 'ClearingProfileCredentials'
    | 'StartingDotNetRestore'
    | 'StartingFunctionDeployment'
    | 'StartingServerlessDeployment'
    | 'UnknownDeploymentTypeError'
    | 'DotNetCommandFailure'
    | 'ProjectPathOrFileDoesNotExist'
    | 'CreatingServerlessPackageOnly'
    | 'CreatingFunctionPackageOnly'
    | 'PackageAndDeployTaskCompleted'
    | 'PackageOnlyTaskCompleted'
    | 'InstallingOrUpdatingLambdaTools'
    | 'LambdaToolsInstallFailed'
    | 'LambdaToolsUpdateFailed'
    | 'LambdaToolsPathNotFound'
