
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type SystemsManagerGetParameterInput = {
    awsCredentials: string
    regionName: string
    readMode: 'single' | 'hierarchy'
    parameterName: string
    parameterVersion: string
    parameterPath: string
    recursive: boolean
    singleNameTransform: 'none' | 'leaf' | 'substitute' | 'custom'
    hierarchyNameTransform: 'none' | 'leaf' | 'substitute'
    customVariableName: string
    replacementPattern: string
    replacementText: string
    globalMatch: boolean
    caseInsensitiveMatch: boolean
    logRequest: boolean
    logResponse: boolean
}

export type SystemsManagerGetParameterMessages = 
    | 'ReadingParameterHierarchy'
    | 'SettingVariable'
    | 'TransformedParameterName'
    | 'UsingParameterNameForVariable'
    | 'TaskCompleted'
    | 'InvalidParameterVersion'
    | 'UnknownReadMode'
    | 'ErrorParametersEmpty'
