
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type SecretsManagerGetSecretInput = {
    awsCredentials: string
    regionName: string
    secretIdOrName: string
    variableName: string
    versionId: string
    versionStage: string
    logRequest: boolean
    logResponse: boolean
}

export type SecretsManagerGetSecretMessages = 
    | 'RetrievingSecret'
    | 'TaskCompleted'
