
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type SystemsManagerSetParameterInput = {
    awsCredentials: string
    regionName: string
    parameterName: string
    parameterType: 'String' | 'StringList' | 'SecureString'
    parameterValue: string
    encryptionKeyId: string
    logRequest: boolean
    logResponse: boolean
}

export type SystemsManagerSetParameterMessages = 
    | 'ParameterExistsAndIsSecureString'
    | 'ParameterExistsAndIsNotSecureString'
    | 'ParameterDoesNotExist'
    | 'CreateOrUpdateFailed'
    | 'ErrorTestingParameter'
    | 'TaskCompleted'
