
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type AWSPowerShellModuleScriptInput = {
    awsCredentials: string
    regionName: string
    arguments: string
    scriptType: 'filePath' | 'inline'
    filePath: string
    inlineScript: string
    errorActionPreference: 'stop' | 'continue' | 'silentlyContinue'
    failOnStderr: boolean
    ignoreLASTEXITCODE: boolean
    workingDirectory: string
}

export type AWSPowerShellModuleScriptMessages = 
    | 'GeneratingScript'
    | 'TestingAWSModuleInstalled'
    | 'AWSModuleNotFound'
    | 'InstallingAWSModule'
    | 'ConfiguringRegionFromTaskConfiguration'
    | 'ConfiguringRegionFromTaskVariable'
    | 'RegionConfiguredTo'
    | 'PS_ExitCode'
    | 'PS_FormattedCommand'
    | 'PS_InvalidErrorActionPreference'
    | 'PS_InvalidFilePath'
    | 'PS_UnableToDetermineExitCode'
    | 'ConfiguringProxy'
    | 'ProxyConfigError'
    | 'SkippingProxyConfigDueToAgentVersion'
    | 'CheckingForProxyConfiguration'
    | 'ConfiguringForRoleCredentials'
    | 'ConfiguringForStandardCredentials'
    | 'ConfiguringForRoleCredentialsFromOIDC'
    | 'ConfiguringForTaskVariableCredentials'
    | 'MissingSecretKeyVariable'
