
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type SystemsManagerRunCommandInput = {
    awsCredentials: string
    regionName: string
    documentName: string
    documentParameters: string
    comment: string
    serviceRoleARN: string
    instanceSelector: 'fromInstanceIds' | 'fromTags' | 'fromBuildVariable'
    instanceIds: string
    instanceTags: string
    instanceBuildVariable: string
    maxConcurrency: string
    maxErrors: string
    timeout: string
    notificationArn: string
    notificationEvents: 'All' | 'InProgress' | 'Success' | 'TimedOut' | 'Cancelled' | 'Failed'
    notificationType: 'Command' | 'Invocation'
    outputS3BucketName: string
    outputS3KeyPrefix: string
    commandIdOutputVariable: string
    cloudWatchOutputEnabled: boolean
    cloudWatchLogGroupName: string
    logRequest: boolean
    logResponse: boolean
}

export type SystemsManagerRunCommandMessages = 
    | 'InstanceIdsFromVariableFailed'
    | 'SettingOutputVariable'
    | 'TaskCompleted'
