
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type AWSCLIInput = {
    awsCredentials: string
    regionName: string
    awsCommand: string
    awsSubCommand: string
    awsArguments: string
    failOnStandardError: boolean
}

export type AWSCLIMessages = 
    | 'AWSCLINotInstalled'
    | 'AwsReturnCode'
