
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type LambdaInvokeFunctionInput = {
    awsCredentials: string
    regionName: string
    functionName: string
    payload: string
    invocationType: 'Event' | 'RequestResponse'
    outputVariable: string
    logType: 'None' | 'Tail'
    logRequest: boolean
    logResponse: boolean
}

export type LambdaInvokeFunctionMessages = 
    | 'InvokingFunction'
    | 'FunctionInvokeFailed'
    | 'SettingOutputVariable'
    | 'ReceivedOutput'
    | 'FunctionDoesNotExist'
    | 'TaskCompleted'
