
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type ECRPullImageInput = {
    awsCredentials: string
    regionName: string
    repository: string
    imageSource: 'imagetag' | 'imagedigest'
    imageTag: string
    imageDigest: string
    outputVariable: string
    logRequest: boolean
    logResponse: boolean
}

export type ECRPullImageMessages = 
    | 'PullImageWithDigest'
    | 'PullImageWithTag'
    | 'PullingImage'
    | 'InvokingDockerCommand'
    | 'RequestingAuthToken'
    | 'FailureToObtainAuthToken'
    | 'NoValidEndpoint'
    | 'TaskCompleted'
    | 'SettingOutputVariable'
