
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type CloudFormationCreateOrUpdateStackInput = {
    awsCredentials: string
    regionName: string
    stackName: string
    templateSource: 'file' | 'url' | 's3' | 'usePrevious'
    templateFile: string
    s3BucketName: string
    s3ObjectKey: string
    templateUrl: string
    templateParametersSource: 'file' | 'inline'
    templateParametersFile: string
    templateParameters: string
    useChangeSet: boolean
    changeSetName: string
    description: string
    includeNestedStacks: boolean
    autoExecuteChangeSet: boolean
    capabilityIAM: boolean
    capabilityNamedIAM: boolean
    capabilityAutoExpand: boolean
    roleARN: string
    resourceTypes: string
    notificationARNs: string
    tags: string
    monitorRollbackTriggers: boolean
    monitoringTimeInMinutes: string
    rollbackTriggerARNs: string
    onFailure: 'DO_NOTHING' | 'ROLLBACK' | 'DELETE'
    disableRollback: boolean
    warnWhenNoWorkNeeded: boolean
    outputVariable: string
    captureStackOutputs: 'ignore' | 'asVariables' | 'asJSON'
    captureAsSecuredVars: boolean
    timeoutInMins: string
    logRequest: boolean
    logResponse: boolean
}

export type CloudFormationCreateOrUpdateStackMessages = 
    | 'CheckingForStackExistence'
    | 'StackLookupFailed'
    | 'StackExists'
    | 'StackDoesNotExist'
    | 'CreateStack'
    | 'UpdateStack'
    | 'LoadingTemplateFile'
    | 'TemplateFileDoesNotExist'
    | 'LoadingTemplateParametersFile'
    | 'LoadingTemplateParameters'
    | 'ParametersLoadSucceeded'
    | 'ParametersLoadFailed'
    | 'StackCreated'
    | 'StackCreationFailed'
    | 'StackCreateRequestFailed'
    | 'StackUpdated'
    | 'StackUpdateFailed'
    | 'StackUpdateRequestFailed'
    | 'WaitingForStackCreation'
    | 'WaitingForStackUpdate'
    | 'TaskCompleted'
    | 'NoWorkToDo'
    | 'ChangeSetCreationFailed'
    | 'WaitingForChangeSetValidation'
    | 'ChangeSetValidated'
    | 'ChangeSetValidationFailed'
    | 'ExecutingChangeSet'
    | 'ExecuteChangeSetFailed'
    | 'SettingOutputVariable'
    | 'CheckingForExistingChangeSet'
    | 'ChangeSetExists'
    | 'ChangeSetLookupFailed'
    | 'DeletingExistingChangeSet'
    | 'FailedToDeleteChangeSet'
    | 'AddingCapability'
    | 'AddingTag'
    | 'AutoExecuteChangeSetOption'
    | 'CreatingChangeSet'
    | 'NoParametersFileSpecified'
    | 'ParametersFileDoesNotExist'
    | 'UploadingTemplate'
    | 'FailedToLoadTemplateFile'
    | 'TemplateUploadFailed'
    | 'AddingRollbackTrigger'
    | 'InvalidTriggerMonitoringTime'
    | 'ExceededMaxRollbackTriggers'
    | 'CreatingStackOutputVariable'
    | 'UpdatingStackWithPreviousTemplate'
    | 'UsePreviousTemplateIsInvalidWhenCreatingStack'
    | 'ProcessingStackOutputsToBuildVariables'
    | 'ProcessingStackOutputsToJsonBlobBuildVariable'
    | 'SkippingStackOutputsProcessing'
    | 'SettingCustomTimeout'
    | 'ErrorRetrievingStackOutputs'
