
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type SecretsManagerCreateOrUpdateSecretInput = {
    awsCredentials: string
    regionName: string
    secretNameOrId: string
    description: string
    secretValueSource: 'inline' | 'file'
    secretValue: string
    secretValueType: 'string' | 'binary'
    secretValueFile: string
    kmsKeyId: string
    autoCreateSecret: boolean
    tags: string
    arnOutputVariable: string
    versionIdOutputVariable: string
    logRequest: boolean
    logResponse: boolean
}

export type SecretsManagerCreateOrUpdateSecretMessages = 
    | 'UpdatingSecret'
    | 'SecretNotFound'
    | 'SecretNotFoundAutoCreating'
    | 'SecretCreated'
    | 'SecretCreationFailed'
    | 'SecretUpdateFailed'
    | 'AddingTag'
    | 'SettingVersionIdOutputVariable'
    | 'SettingArnOutputVariable'
    | 'TooManyTags'
    | 'CreateSecretCompleted'
    | 'UpdateSecretCompleted'
