
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type ECRPushImageInput = {
    awsCredentials: string
    regionName: string
    imageSource: 'imagename' | 'imageid'
    sourceImageName: string
    sourceImageTag: string
    sourceImageId: string
    repositoryName: string
    pushTag: string
    autoCreateRepository: boolean
    forceDockerNamingConventions: boolean
    removeDockerImage: boolean
    outputVariable: string
    logRequest: boolean
    logResponse: boolean
}

export type ECRPushImageMessages = 
    | 'PushImageWithId'
    | 'PushImageWithName'
    | 'RequestingAuthToken'
    | 'AddingTag'
    | 'PushingImage'
    | 'RemovingImage'
    | 'InvokingDockerCommand'
    | 'TestingForRepository'
    | 'CreatingRepository'
    | 'SettingOutputVariable'
    | 'TaskCompleted'
    | 'FailureToObtainAuthToken'
    | 'NoValidEndpoint'
