
/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */


/*!
 * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT
 */

    
/* NOTE! this file is auto-generated by generateResources.ts, do not edit it by hand. */

export type SendMessageInput = {
    awsCredentials: string
    regionName: string
    messageTarget: 'topic' | 'queue'
    message: string
    topicArn: string
    queueUrl: string
    delaySeconds: string
    logRequest: boolean
    logResponse: boolean
}

export type SendMessageMessages = 
    | 'TopicDoesNotExist'
    | 'QueueDoesNotExist'
    | 'SendingToTopic'
    | 'SendingToQueue'
    | 'SendingToQueueWithDelay'
    | 'SendError'
    | 'TaskCompleted'
